# First Data Set

In [1]:
import numpy as np
import pandas as pd

df1 =pd.read_csv(r'C:\_Working\PAT_20201019\debug\cmp\d1.csv')

# df1 = df1.drop(columns=['AOI','LocationIDStack','RatingGroup'])
df1 = df1.sort_values(by=['PseudoPolicyID','PseudoLayerID','Retention','Limit']).reset_index(drop=True)
df1

,Limit,Retention,Premium,Participation,AOI,LocationIDStack,RatingGroup,OriginalPolicyID,PseudoPolicyID,PseudoLayerID,PolLAS,DedLAS
0,6.891514e+06,8.269816e+06,0.000000,0.00000,1.529916e+07,2071035,30,883100,883100_2071035,1,231696.935061,203071.368477
1,6.891514e+06,1.516133e+07,0.000000,0.00000,1.529916e+07,2071035,30,883100,883100_2071035,2,244938.290076,231696.935087
2,4.824059e+07,2.205284e+07,4551.539227,0.15075,1.529916e+07,2071035,30,883100,883100_2071035,3,258995.921996,244938.290089
3,6.891514e+06,5.513211e+06,0.000000,0.00000,5.513211e+06,2071036,30,883100,883100_2071036,1,122097.542907,106721.607055
4,6.891514e+06,1.240472e+07,0.000000,0.00000,5.513211e+06,2071036,30,883100,883100_2071036,2,126304.020248,122097.542919
...,...,...,...,...,...,...,...,...,...,...,...,...
101752,3.519020e+08,1.395100e+08,NaN,0.00000,1.395100e+08,2441648,32,910084,910084_2441648,1,423153.350214,405312.512012
101753,3.519020e+08,2.076281e+08,NaN,0.00000,2.076281e+08,2441649,32,910084,910084_2441649,1,428044.687778,417403.498137
101754,3.519020e+08,2.363609e+08,NaN,0.00000,3.053678e+08,2441650,32,910084,910084_2441650,1,431099.118413,422693.077493
101755,3.519020e+08,2.363609e+08,NaN,0.00000,3.098046e+08,2441651,32,910084,910084_2441651,1,435445.626365,427039.415123
101756,3.519020e+08,2.363609e+08,NaN,0.00000,3.270975e+08,2441652,32,910084,910084_2441652,1,435445.626365,427039.415123

# Second Data set

In [2]:
df2 =pd.read_csv(r'C:\_Working\PAT_20201019\debug\cmp\d2.csv')
df2 = df2.sort_values(by=['PseudoPolicyID','PseudoLayerID','Retention', 'Limit']).reset_index(drop=True)

df2

,Limit,Retention,Premium,Participation,AOI,LocationIDStack,RatingGroup,OriginalPolicyID,PseudoPolicyID,PseudoLayerID,PolLAS,DedLAS
0,6.891514e+06,8.269816e+06,0.000000,0.00000,1.529916e+07,2071035,30,883100,883100_2071035,1,231696.935060,203071.368477
1,6.891514e+06,1.516133e+07,0.000000,0.00000,1.529916e+07,2071035,30,883100,883100_2071035,2,244938.290075,231696.935086
2,4.824059e+07,2.205284e+07,4551.539227,0.15075,1.529916e+07,2071035,30,883100,883100_2071035,3,258995.921996,244938.290088
3,6.891514e+06,5.513211e+06,0.000000,0.00000,5.513211e+06,2071036,30,883100,883100_2071036,1,122097.542906,106721.607055
4,6.891514e+06,1.240472e+07,0.000000,0.00000,5.513211e+06,2071036,30,883100,883100_2071036,2,126304.020248,122097.542919
...,...,...,...,...,...,...,...,...,...,...,...,...
101752,3.519020e+08,1.395100e+08,NaN,0.00000,1.395100e+08,2441648,32,910084,910084_2441648,1,423153.350214,405312.512012
101753,3.519020e+08,2.076281e+08,NaN,0.00000,2.076281e+08,2441649,32,910084,910084_2441649,1,428044.687778,417403.498137
101754,3.519020e+08,2.363609e+08,NaN,0.00000,3.053678e+08,2441650,32,910084,910084_2441650,1,431099.118413,422693.077493
101755,3.519020e+08,2.363609e+08,NaN,0.00000,3.098046e+08,2441651,32,910084,910084_2441651,1,435445.626365,427039.415123
101756,3.519020e+08,2.363609e+08,NaN,0.00000,3.270975e+08,2441652,32,910084,910084_2441652,1,435445.626365,427039.415123

# Transform

In [3]:

# df2 = df2.rename(columns={'status':'flag'})

# df1 = df1.sort_values(by=['PseudoPolicyID','FacAttachment','FacLimit']).reset_index(drop=True)

print(df1.shape, df2.shape)
pd.DataFrame(df1.dtypes,columns=['DF1']).join(pd.DataFrame(df2.dtypes,columns=['DF2']),how='outer')

(101757, 12) (101757, 12)

                      DF1      DF2
Limit             float64  float64
Retention         float64  float64
Premium           float64  float64
Participation     float64  float64
AOI               float64  float64
LocationIDStack     int64    int64
RatingGroup         int64    int64
OriginalPolicyID    int64    int64
PseudoPolicyID     object   object
PseudoLayerID       int64    int64
PolLAS            float64  float64
DedLAS            float64  float64

# Comparison

In [4]:
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype
from pandas.api.types import is_float_dtype


cmp =pd.DataFrame(columns=['name','type', 'diff','df1_min','df2_min','df1_max','df2_max','df1_nan','df2_nan'])
for c in df1.columns:
    if is_string_dtype(df1[c]):
        if np.all(df1[c].fillna(value="") != df2[c].fillna(value="")):
            cmp = cmp.append({'name': c,'type':df1[c].dtype,'diff':'NO'}, ignore_index=True)
        else:
            cmp = cmp.append({'name': c,'type':df1[c].dtype,'diff':'YES'}, ignore_index=True)
    elif is_float_dtype(df1[c]):
        df1.loc[df1[c].astype('float') > 1e20,[c]] = 1e20
        df2.loc[df2[c].astype('float') > 1e20,[c]] = 1e20
        dif = np.max(np.abs(df1[c].astype('float') - df2[c].astype('float')))
        # if dif > 1e-8:
        #     dif = np.max( 
        #             np.abs(df1[c].astype('float') - df2[c].astype('float')) /
        #             (np.maximum(np.abs(df1[c].astype('float')), np.abs(df2[c].astype('float'))) + 1e-10 )
        #         )            
        cmp = cmp.append({'name': c,'type':df1[c].dtype,'diff':dif,
            'df1_min':np.min(df1[c]),
            'df2_min':np.min(df2[c]),
            'df1_max':np.max(df1[c]),
            'df2_max':np.max(df2[c]),
            'df1_nan':np.sum(np.isnan(df1[c])),
            'df2_nan':np.sum(np.isnan(df2[c]))
        }, ignore_index=True)
    elif is_numeric_dtype(df1[c]):
        dif = np.max(np.abs(df1[c] - df2[c]))
        cmp = cmp.append({'name': c,'type':df1[c].dtype,'diff':dif,
            'df1_min':np.min(df1[c]),
            'df2_min':np.min(df2[c]),
            'df1_max':np.max(df1[c]),
            'df2_max':np.max(df2[c]),
            'df1_nan':np.sum(np.isnan(df1[c])),
            'df2_nan':np.sum(np.isnan(df2[c]))
        }, ignore_index=True)
    else:
        cmp = cmp.append({'name': c,'type':df1[c].dtype,'diff':'UNK'}, ignore_index=True)

cmp

,name,type,diff,df1_min,df2_min,df1_max,df2_max,df1_nan,df2_nan
0,Limit,float64,0.003273,2.500000e+06,2.500000e+06,2.650000e+09,2.650000e+09,0,0
1,Retention,float64,0.01,9.000000e+00,9.000000e+00,4.000500e+08,4.000500e+08,0,0
2,Premium,float64,0.000004,0.000000e+00,0.000000e+00,4.283277e+05,4.283277e+05,72,72
3,Participation,float64,0.0,0.000000e+00,0.000000e+00,5.000000e-01,5.000000e-01,0,0
4,AOI,float64,0.0,9.000000e+00,9.000000e+00,2.647021e+09,2.647021e+09,0,0
5,LocationIDStack,int64,0.0,6.943730e+05,6.943730e+05,2.441652e+06,2.441652e+06,0,0
6,RatingGroup,int64,0.0,1.000000e+00,1.000000e+00,3.900000e+01,3.900000e+01,0,0
7,OriginalPolicyID,int64,0.0,8.831000e+05,8.831000e+05,9.100840e+05,9.100840e+05,0,0
8,PseudoPolicyID,object,YES,NaN,NaN,NaN,NaN,NaN,NaN
9,PseudoLayerID,int64,0,1.000000e+00,1.000000e+00,5.000000e+00,5.000000e+00,0,0
10,PolLAS,float64,0.000023,2.683237e+01,2.683237e+01,4.903995e+05,4.903995e+05,0,0
11,DedLAS,float64,0.000117,8.981306e+00,8.981306e+00,4.446984e+05,4.446984e+05,0,0